# Generated by Django 4.1.1 on 2023-04-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_employer'),
        ('accounts', '0005_alter_jobseeker_looking_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('unemployed', models.IntegerField()),
                ('employed', models.IntegerField()),
                ('unemployment_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='IndustrialRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('complainant_name', models.CharField(max_length=100)),
                ('complainant_gender', models.CharField(max_length=10)),
                ('complaint_nature', models.CharField(max_length=200)),
                ('employer_name', models.CharField(max_length=100)),
                ('investigating_officer_name', models.CharField(max_length=100)),
                ('complaint_status', models.CharField(max_length=50)),
                ('settlement_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='industry_trends/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('benefits', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee_turnover_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('most_common_job_title', models.CharField(max_length=255)),
                ('most_common_skill', models.CharField(max_length=255)),
                ('job_posting_frequency', models.IntegerField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
    ]
