# Generated by Django 4.1.1 on 2023-08-28 16:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jobs.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('location', models.CharField(default='Freetown', max_length=200)),
                ('contract', models.CharField(choices=[('', 'Select a contract type'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Freelance', 'Freelance')], max_length=100)),
                ('experience', models.CharField(choices=[('', 'Select an experience level'), ('No experience', 'No experience'), ('1 year', '1 year'), ('2 years', '2 years'), ('3 years', '3 years'), ('5 years', '5 years'), ('10 years', '10 years'), ('More than 10 years', 'More than 10 years')], max_length=200)),
                ('qualification', models.CharField(default='Bachelors', max_length=200)),
                ('requirements', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=jobs.models.user_directory_path)),
                ('job_status', models.CharField(choices=[('', 'Select a job status'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateField()),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('updated', models.DateField(auto_now=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.employer')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'ordering': ['-updated', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='sectors')),
            ],
            options={
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_job', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved Jobs',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.sector'),
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Applied Jobs',
            },
        ),
    ]
