# Generated by Django 4.1.1 on 2023-04-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('company_size', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
    ]
