# Generated by Django 4.1.1 on 2023-08-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('', 'Select a district'), ('Bo', 'Bo'), ('Bonthe', 'Bonthe'), ('Bombali', 'Bombali'), ('Falaba', 'Falaba'), ('Kailahun', 'Kailahun'), ('Kambia', 'Kambia'), ('Kenema', 'Kenema'), ('Koinadugu', 'Koinadugu'), ('Karene', 'Karene'), ('Kono', 'Kono'), ('Moyamba', 'Moyamba'), ('Port Loko', 'Port Loko'), ('Pujehun', 'Pujehun'), ('Tonkolili', 'Tonkolili'), ('Western Rural', 'Western Rural'), ('Western Urban', 'Western Urban'), ('International', 'International')], max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(choices=[('', 'Select a qualification'), ('High School', 'High School'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('College', 'College'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctrate', 'Doctrate')], max_length=200),
        ),
    ]
