# Generated by Django 4.1.1 on 2023-07-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='location',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='government',
            old_name='location',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='jobseeker',
            old_name='location',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
        migrations.RemoveField(
            model_name='government',
            name='status',
        ),
    ]
