# Generated by Django 4.1.1 on 2023-09-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSeekerContact',
        ),
        migrations.DeleteModel(
            name='JobSeekerEducation',
        ),
        migrations.DeleteModel(
            name='JobSeekerExperience',
        ),
        migrations.DeleteModel(
            name='JobSeekerInfo',
        ),
        migrations.DeleteModel(
            name='JobSeekerProject',
        ),
    ]
