# Generated by Django 4.1.1 on 2022-12-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='grad_year',
            field=models.CharField(max_length=4),
        ),
    ]
