# Generated by Django 4.1.1 on 2023-09-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_jobseeker_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
