# Generated by Django 4.1.1 on 2023-07-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_company_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='status',
        ),
    ]
