# Generated by Django 4.1.1 on 2023-09-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_jobseeker_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='district',
            field=models.CharField(choices=[('', 'Select a district'), ('Bo', 'Bo'), ('Bonthe', 'Bonthe'), ('Bombali', 'Bombali'), ('Falaba', 'Falaba'), ('Kailahun', 'Kailahun'), ('Kambia', 'Kambia'), ('Kenema', 'Kenema'), ('Koinadugu', 'Koinadugu'), ('Karene', 'Karene'), ('Kono', 'Kono'), ('Moyamba', 'Moyamba'), ('Port Loko', 'Port Loko'), ('Pujehun', 'Pujehun'), ('Tonkolili', 'Tonkolili'), ('Western Rural', 'Western Rural'), ('Western Urban', 'Western Urban'), ('International', 'International')], max_length=250),
        ),
        migrations.AlterField(
            model_name='government',
            name='district',
            field=models.CharField(choices=[('', 'Select a district'), ('Bo', 'Bo'), ('Bonthe', 'Bonthe'), ('Bombali', 'Bombali'), ('Falaba', 'Falaba'), ('Kailahun', 'Kailahun'), ('Kambia', 'Kambia'), ('Kenema', 'Kenema'), ('Koinadugu', 'Koinadugu'), ('Karene', 'Karene'), ('Kono', 'Kono'), ('Moyamba', 'Moyamba'), ('Port Loko', 'Port Loko'), ('Pujehun', 'Pujehun'), ('Tonkolili', 'Tonkolili'), ('Western Rural', 'Western Rural'), ('Western Urban', 'Western Urban'), ('International', 'International')], max_length=250),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='district',
            field=models.CharField(choices=[('', 'Select a district'), ('Bo', 'Bo'), ('Bonthe', 'Bonthe'), ('Bombali', 'Bombali'), ('Falaba', 'Falaba'), ('Kailahun', 'Kailahun'), ('Kambia', 'Kambia'), ('Kenema', 'Kenema'), ('Koinadugu', 'Koinadugu'), ('Karene', 'Karene'), ('Kono', 'Kono'), ('Moyamba', 'Moyamba'), ('Port Loko', 'Port Loko'), ('Pujehun', 'Pujehun'), ('Tonkolili', 'Tonkolili'), ('Western Rural', 'Western Rural'), ('Western Urban', 'Western Urban'), ('International', 'International')], max_length=250),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
