# Generated by Django 4.1.1 on 2023-09-13 14:51

import accounts.models
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobseeker_about_alter_jobseeker_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=50, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='profile_pic',
            field=models.FileField(upload_to=accounts.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg']), accounts.models.validate_image_type, accounts.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf']), accounts.models.validate_file_mimetype, accounts.models.validate_file_size]),
        ),
    ]
