# Generated by Django 4.1.1 on 2023-09-13 15:09

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_jobseeker_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.FileField(upload_to=accounts.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg']), accounts.models.validate_image_type, accounts.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='government',
            name='logo',
            field=models.FileField(upload_to=accounts.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg']), accounts.models.validate_image_type, accounts.models.validate_file_size]),
        ),
    ]
