# Generated by Django 4.1.1 on 2023-09-15 16:52

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_employer_company_logo_alter_government_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_certificate',
            field=models.FileField(upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf']), accounts.models.validate_file_mimetype, accounts.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='employment_status',
            field=models.CharField(choices=[('', 'Select employment status'), ('Employed', 'Employed'), ('Self-Employed', 'Self-Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Retired', 'Retired')], max_length=250),
        ),
    ]
