# Generated by Django 4.1.1 on 2023-07-21 15:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(default='images/home-blog1.jpg', upload_to='news/'), size=None)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('author', models.CharField(max_length=250, verbose_name='Author')),
                ('content', models.TextField(verbose_name='Content')),
                ('tag', models.CharField(choices=[('', 'Select a Tag'), ('News', 'News'), ('Events', 'Events')], max_length=200, verbose_name='Tag')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
