# Generated by Django 4.1.1 on 2023-07-24 22:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('author', models.CharField(max_length=250, verbose_name='Author')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('tag', models.CharField(choices=[('', 'Select a Tag'), ('News', 'News'), ('Events', 'Events')], max_length=200, verbose_name='Tag')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/home-blog1.jpg', upload_to='news/')),
                ('news_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news_and_events.newsandevents')),
            ],
        ),
    ]
