# Generated by Django 4.1.1 on 2023-07-19 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsAndEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('author', models.CharField(max_length=250, verbose_name='Author')),
                ('content', models.TextField(verbose_name='Content')),
                ('tag', models.CharField(choices=[('', 'Select a Tag'), ('News', 'News'), ('Events', 'Events')], max_length=200, verbose_name='Tag')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_and_events.images')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
