# Generated by Django 4.1.1 on 2023-07-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandevents',
            name='images',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/home-blog1.jpg', upload_to='news/')),
                ('news_and_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_and_events.newsandevents')),
            ],
        ),
    ]
