# Generated by Django 4.1.1 on 2023-07-24 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='news_event',
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_and_events.image'),
        ),
    ]
