# Generated by Django 4.1.1 on 2023-07-21 13:08

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(default='static/images/home-blog1.jpg', upload_to='news/'), size=None)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='newsandevents',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Published Date'),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='images',
            field=models.ForeignKey(default=datetime.datetime(2023, 7, 21, 13, 8, 40, 273249, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='news_and_events.image'),
            preserve_default=False,
        ),
    ]
