# Generated by Django 4.1.1 on 2023-07-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='image3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='image4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='image5',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
