# Generated by Django 4.1.1 on 2023-07-21 14:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0002_image_alter_newsandevents_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(default='images/home-blog1.jpg', upload_to='news/'), size=None),
        ),
    ]
