# Generated by Django 4.1.1 on 2023-07-20 11:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0002_alter_images_options_remove_images_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='news/'), size=None)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_and_events.image'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
