# Generated by Django 4.1.1 on 2023-07-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0003_image_alter_newsandevents_images_delete_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.CharField(max_length=1000),
        ),
    ]
