# Generated by Django 4.1.1 on 2023-07-24 16:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0003_remove_image_image_remove_image_news_and_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(default='images/home-blog1.jpg', upload_to='news/'), size=None),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
