# Generated by Django 4.1.1 on 2023-07-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0003_alter_image_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created_at',
        ),
    ]
