# Generated by Django 4.1.1 on 2023-07-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0004_alter_image_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandevents',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
