# Generated by Django 4.1.1 on 2023-07-21 15:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0004_remove_image_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(default='images/home-blog1.jpg', upload_to='news/'), size=None),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
