# Generated by Django 4.1.1 on 2023-07-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0005_remove_newsandevents_images_delete_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsandevents',
            options={'ordering': ['-published_date']},
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='created_at',
        ),
    ]
