# Generated by Django 4.1.1 on 2023-07-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0006_alter_newsandevents_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
