# Generated by Django 4.1.1 on 2023-08-28 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('status', models.CharField(choices=[('', 'Select status'), ('Open', 'Open'), ('Closed', 'Closed')], max_length=100, verbose_name='Status')),
                ('lead_instructor', models.CharField(max_length=200)),
                ('fees', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('topic', models.CharField(choices=[('', 'Select a topic'), ('Computer Science, Data Modeling & Analytics', 'Computer Science, Data Modeling & Analytics'), ('Biotechnology & Pharmaceutical', 'Biotechnology & Pharmaceutical'), ('Design & Manufacturing', 'Design & Manufacturing'), ('Innovation', 'Innovation'), ('Real Estate', 'Real Estate'), ('Leadership & Communication', 'Leadership & Communication'), ('Crisis Management', 'Biotechnology & Pharmaceutical'), ('Energy & Sustainability', 'Energy & Sustainability')], max_length=200, verbose_name='Topic')),
                ('learning_outcome', models.TextField(blank=True, max_length=250, null=True, verbose_name='Learning Outcome')),
                ('curriculum', models.TextField(blank=True, max_length=250, null=True, verbose_name='Curriculum')),
                ('updated', models.DateField(auto_now=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-updated', '-created_at'],
            },
        ),
    ]
