# Generated by Django 4.1.1 on 2023-08-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('document', models.FileField(upload_to='documents/')),
                ('download_url', models.URLField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
