# Generated by Django 4.1.1 on 2023-08-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloaddocument',
            name='download_url',
        ),
    ]
