# Generated by Django 4.1.1 on 2023-08-04 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_downloaddocument_download_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloaddocument',
            name='document',
        ),
        migrations.AddField(
            model_name='downloaddocument',
            name='download_url',
            field=models.URLField(default=datetime.datetime(2023, 8, 4, 0, 18, 46, 293430, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
