# Generated by Django 4.1.1 on 2023-08-04 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_remove_downloaddocument_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloaddocument',
            old_name='download_url',
            new_name='url',
        ),
    ]
